### ISSUE TITLE
Creature Movement Issues

### ISSUE THREAD

**Issue by CelticMoonShine** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#36] opened 2019-01-11 17:27 UTC
When dragging a creature to move it, 5 squares in all directions get shaded but movement allows 6 squares. This limit is in place while in Build, Exploration or Cut scene modes, rather unfortunate for the DM adjusting locations before game, cutscenes in which people go father than that, or simply having a creature dash 12 squares

**Comment by cbaggers** [comment] 2019-01-12 21:32
Cheers for the report. It sounds like a duplicate of [this one](https://github.com/Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker/issues/27)so i'm gonna tentatively close this and track the issue over there.

If you feel this is incorrect them please let me know here and I'll reopen this.

**Closed by cbaggers** 2019-01-12 21:32 UTC
