### ISSUE TITLE
"Report Bug" button freezes TaleSpire

### ISSUE THREAD

**Issue by LuPro** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#93] opened 2019-01-26 21:29 UTC
When clicking on "Report Bug" in the "Exit Menu" window (accessible in the top right) the game loads the git page issue tracker site in the default browser. So far so good. But for me this makes the game freeze ("not responding") 100% of the time (4/4 tries)

1. Open "Exit Menu"
2. Press "Report Bug"
3. After ~1-2 seconds the sound (I was playing atmosphere music at the time) stops (game froze)
4. No amount of waiting (waited once for nearly 10 minutes) makes it recover, it just stays at the windows "talespire is not responding..." state

Additional Info:
Using Windows 10, version 1803 build 17134.523 and Firefox 64.0.2 64-bit (can provide more detail if needed)

This happened for me no matter if custom atmosphere was activated or not, All tries were done in GM mode, tested in building and non-building mode (I don't think that it makes a difference, but who knows)

**Comment by cbaggers** [comment] 2019-02-08 07:09
@LuPro Thanks for this report. I've been unable to reproduce it with the latest Firefox. Is this issue still occurring for you?

**Comment by LuPro** [comment] 2019-02-09 16:07
It seems to have randomly fixed itself - I think it might have been my antivirus, because when I tested it right now it worked as expected, but my antivirus showed a pop-up and wanted to "block a threat from TaleSpire.exe" - which it didn't show before.

**Comment by cbaggers** [comment] 2019-02-27 14:46
Thanks for the update, i've been testing this from time to time and havent been able to reproduce it so I'm gonna close this for now. Do feel free to resurrect if it comes back :)

**Closed by cbaggers** 2019-02-27 14:46 UTC
Labels: Tracking internally
